import { InputType, InputTypeValue, InputTypeLayout } from "types/formSettings";

export const initialFormSettings = [
  {
    name: "name",
    value: "BatMan" as InputTypeValue,
    type: "text" as InputType,
    label: "Your name",
    layout: "column" as InputTypeLayout,
  },
  {
    name: "playerMarks",
    value: "😉" as InputTypeValue,
    type: "select" as InputType,
    label: "Cell icon",
    options: ["😉", "😎", "🙃", "😋", "🤪"],
    layout: "row" as InputTypeLayout,
  },
  {
    name: "colorLiveCell",
    value: "#00ff00" as InputTypeValue,
    type: "color" as InputType,
    label: "Color of live cell",
    layout: "row" as InputTypeLayout,
  },
  {
    name: "colorDeadCell",
    value: "#ffffff" as InputTypeValue,
    type: "color" as InputType,
    label: "Color of dead cell",
    layout: "row" as InputTypeLayout,
  },
  {
    name: "xSize",
    value: 15 as InputTypeValue,
    type: "number" as InputType,
    label: "Size axis X",
    min: 5,
    layout: "row" as InputTypeLayout,
  },
  {
    name: "ySize",
    value: 15 as InputTypeValue,
    type: "number" as InputType,
    label: "Size axis Y",
    min: 5,
    layout: "row" as InputTypeLayout,
  },
  {
    name: "fillPercentage",
    value: 20 as InputTypeValue,
    type: "number" as InputType,
    label: "Fill percentage",
    min: 0,
    max: 100,
    layout: "row" as InputTypeLayout,
  },
  {
    name: "speed",
    value: 1 as InputTypeValue,
    type: "number" as InputType,
    label: "Speed",
    min: 1,
    max: 5,
    layout: "row" as InputTypeLayout,
  },
  {
    name: "idImage",
    value: 1 as InputTypeValue,
    type: "number" as InputType,
    label: "Image number",
    min: 1,
    max: 99,
    layout: "row" as InputTypeLayout,
  },
];
